"""OpenAI streaming event-type constants."""

OPENAI_EVENT_RESPONSE_CREATED = "response.created"
OPENAI_EVENT_TEXT_DELTA = "response.output_text.delta"
OPENAI_EVENT_TEXT_DONE = "response.output_text.done"
OPENAI_EVENT_REASONING_DELTA = "response.reasoning_text.delta"
OPENAI_EVENT_REASONING_DONE = "response.reasoning_text.done"
OPENAI_EVENT_FUNCTION_ARGS_DELTA = "response.function_call_arguments.delta"
OPENAI_EVENT_FUNCTION_ARGS_DONE = "response.function_call_arguments.done"
OPENAI_EVENT_OUTPUT_ITEM_ADDED = "response.output_item.added"
OPENAI_EVENT_OUTPUT_ITEM_DONE = "response.output_item.done"
OPENAI_EVENT_COMPLETED = "response.completed"
OPENAI_EVENT_FAILED = "response.failed"
