"""LLM-related constants."""

from omniagent.constants.llm.general import (
    LLM_MODEL_PROVIDER_INFERENCE_MAP_DEFAULT,
    LLM_PROVIDER_DEFAULT_API_TYPE_MAP_DEFAULT,
    LLM_TOOL_CHOICE_AUTO,
    OPENAI,
)
from omniagent.constants.llm.models import GPT_4_1, GPT_4_1_MINI, TEXT_EMBEDDING_3_SMALL
from omniagent.constants.llm.openai import (
    LLM_API_TYPE_CHAT_COMPLETION,
    LLM_API_TYPE_RESPONSES,
    OPENAI_CHAT_COMPLETIONS_ALLOWED_REQUEST_KWARGS,
    OPENAI_RESPONSES_ALLOWED_REQUEST_KWARGS,
)

__all__ = [
    "OPENAI",
    "LLM_API_TYPE_RESPONSES",
    "LLM_API_TYPE_CHAT_COMPLETION",
    "GPT_4_1",
    "GPT_4_1_MINI",
    "TEXT_EMBEDDING_3_SMALL",
    "LLM_TOOL_CHOICE_AUTO",
    "LLM_MODEL_PROVIDER_INFERENCE_MAP_DEFAULT",
    "LLM_PROVIDER_DEFAULT_API_TYPE_MAP_DEFAULT",
    "OPENAI_RESPONSES_ALLOWED_REQUEST_KWARGS",
    "OPENAI_CHAT_COMPLETIONS_ALLOWED_REQUEST_KWARGS",
]
